version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Building the Python function"
  post_build:
    commands:
      - echo "Running the Python function"
      - python lambda_handler.py